### ISSUE TITLE
[bug] Cannot instantiate Panda3dQWidget

### ISSUE THREAD

**Issue by gabrielebndn** [duburcqa/jiminy#369]
Intantiating `Panda3dQWidget` raises the following exception:

```
Traceback (most recent call last):
  File "/install/bin/logstudio", line 33, in <module>
    sys.exit(load_entry_point('logstudio', 'console_scripts', 'logstudio')())
  File "/src/python/logstudio/src/wdc/logstudio/logstudio.py", line 46, in main
    win.init_gui()
  File "/src/python/logstudio/src/wdc/logstudio/main_window.py", line 149, in init_gui
    self.init_widgets()
  File "/src/python/logstudio/src/wdc/logstudio/main_window.py", line 67, in init_widgets
    self.widgets.viewer3d.init(self.logfile_path, self.data_source)
  File "/src/python/logstudio/src/wdc/logstudio/viewer3d_widget.py", line 136, in init
    Viewer.open_gui(start_if_needed=True)
  File "/install/lib/python3.8/site-packages/jiminy_py/viewer/viewer.py", line 555, in fct_safe
    return fct(*args, **kwargs)
  File "/install/lib/python3.8/site-packages/jiminy_py/viewer/viewer.py", line 802, in open_gui
    Viewer.__connect_backend(start_if_needed)
  File "/install/lib/python3.8/site-packages/jiminy_py/viewer/viewer.py", line 555, in fct_safe
    return fct(*args, **kwargs)
  File "/install/lib/python3.8/site-packages/jiminy_py/viewer/viewer.py", line 1171, in __connect_backend
    client = Panda3dQWidget()
  File "/install/lib/python3.8/site-packages/jiminy_py/viewer/panda3d/panda3d_widget.py", line 22, in __init__
    super(QtWidgets.QWidget, self).__init__(parent=parent)
TypeError: PySide2.QtCore.QObject isn't a direct base class of Panda3dQWidget
```

**Comment by gabrielebndn** [comment]
@duburcqa would you mind quickly deploying a new release with this fix? We need it for our tools to work. PS: I opened the PR on master, but I can do it on dev if you prefer
